server:
  port: 8080
spring:
  security:
    user:
      name: ENC(d29ghxZptoS5y5n7zymFzAGRL3Gmo6Z1Zn7cU+T+KeZzm/pabyQUa9gzjuaIN1np)
      password: ENC(LMW3gn/makBWeiu/U9Kq9HDQyd6PFuHiDdmmF6CCMQ+wpH+/lnkLOW02iB/57nKe)
      roles: ADMIN
  # 配置数据源
  datasource:
    url: jdbc:mysql://database-test.cxlggy9iwoub.us-east-1.rds.amazonaws.com:3306/projects?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(vOZM61g/X2EEs0JJyfN/M6sSB1yI2V/g853ynElhusA01PKba5cxLFlJjCGYDf4u)
    password: ENC(rsxkSzOexAi20Q8XoGuGo2EOAGJsLlb/PQ+QBsnE/5FP9pYIATf1rrUBUhaB9/lTbOvOou8yBSbZqcmHz044YQ==)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select '1'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml

#showSql
logging:
  level:
    com:
      leon:
        dynamiccolumn:
          dao: debug

file:
  tmp: /Users/songwenlong/Desktop/dynamiccolumn/tmp

