server:
  port: 8080
spring:
  security:
    user:
      name: ENC(4W5zwiZqFY9P29Yp/+AbunpFZVvx6SRinj/EEZNqZ4VyjHMebL+1cHQRGESE6NEC)
      password: ENC(xe2F2chWyP/ghteIR7MjATTjInhgVq04hGdzLZhLgyMiN65d6M/ELApVLRYudxdb)
      roles: ADMIN
  # 配置数据源
  datasource:
    url: jdbc:mysql://database-resit.cxlggy9iwoub.us-east-1.rds.amazonaws.com:3306/sys?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ENC(XF6jPBBiadzca4OvGKKg00ubP3NHe82ggoJS6+766HKfqKhC71wEhbaMVG080D2D)
    password: ENC(8HDrfh0aj4O9eYo+IP/vbg93hEE7FIU5dskfNRHaxk+3mH6LMxfY/iknVrQi7Yv1wC6yQtkVzazmkgoKdlwfKw==)
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select '1'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml

#showSql
logging:
  level:
    com:
      leon:
        dynamiccolumn:
          dao: debug

file:
  tmp: /Users/songwenlong/Desktop/dynamiccolumn/tmp

